### ISSUE TITLE
Device integrity fails on rooted device

### ISSUE THREAD

**Issue by Amby713** [crdroidandroid/android_device_xiaomi_apollon#2]
I root my phone and it works fine, but they changed some code to check fingerprint against device model age falls.

I do not know much about what they means, but do know the root breaks it. Another group has a patch to fix it and I'm wondering if you can add it to the rom so it's fixed. You can find patch here  

https://gerrit.hentaios.com/c/hentaiOS/platform_frameworks_base/+/624

![Screenshot_20230209-201855_Play Integrity API Checker](https://user-images.githubusercontent.com/105613369/218011111-6d4521a7-4e53-44f2-9e61-4ec91f08585b.png)

**Comment by gwolf2u** [comment]
issue been fixed
with next update should be ok
